openapi: 3.0.1
info:
  title: NxtPort PortVoyages API
  termsOfService: 'https://www.nxtport.eu/General-Terms-And-Conditions'
  version: '1.0'
  contact:
    email: support@nxtport.com
servers:
  - url: 'https://api-uat.nxtport.com/portvoyages/v1/'
    description: UAT Environment
  - url: 'https://api.nxtport.com/portvoyages/v1/'
    description: PRD Environment

paths:
  /voyages:
    get:
      description: PortVoyages API
      operationId: getPortVoyages
      parameters:
        - name: date
          in: query
          description: 'Referentiedatum die bepaalt welke data moet worden opgehaald: op basis van deze date/time gaat systeem enkel gewijzigde reisdata ophalen vanaf het opgegeven moment. Je kan tot max 6 uur terug. Formaat is "yyyy-MM-ddThh:mm:ssZ".'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A valid response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PortVoyageResponseDTO'
        '403':
          description: Forbidden
        '429':
          description: Too many requests
        default:
          description: Unexpected Problem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortOfAntwerpProblem'
security:
  - bearerAuth: []
  - ApiKeyAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT authorization token using the Bearer scheme. Different for each user of the API. Keep in mind that you have to put the word \"Bearer\" and then a space in front of the access token. For example \"Bearer f8e6d39a81fc4d31957086fe03630858\"."
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
      description: API subscription key. Assigned by NxtPort to your organization.
  schemas:
    PortVoyageShipResponseDTO:
      type: object
      properties:
        ship_name:
          type: string
          description: Naam schip
        imo_number:
          type: string
          description: IMO nummer
        mmsi_number:
          type: string
          description: MMSI nummer
        call_sign:
          type: string
          description: Callsign
        flag_code:
          type: string
          description: Vlag
        ship_type:
          type: string
          description: Scheepstype
        gross_tonnage:
          type: integer
          description: Bruto tonnenmaat
          format: int64
    PtaResponseDTO:
      type: object
      properties:
        location:
          type: string
        pt:
          type: string
          format: date-time
    LockResponseDTO:
      type: object
      properties:
        lock_code:
          type: string
        direction:
          type: string
    TravelPlanResponseDTO:
      type: object
      properties:
        time:
          type: string
          format: date-time
        time_type:
          type: string
        location:
          type: string
        location_name:
          type: string
        source:
          type: string
    PortVoyagePersonsOnBoardResponseDTO:
      type: object
      properties:
        name_captain:
          type: string
          description: Naam capitein
        crew_members_count:
          type: integer
          description: Aantal crewmembers aan boord
          format: int32
        passengers_count:
          type: integer
          description: Aantal passagiers aan boord
          format: int32
        sent:
          type: boolean
          description: bericht verstuurt
    PortVoyageResponseDTO:
      type: object
      properties:
        voyage_number:
          type: string
          description: Reisnummer
        stay_number:
          type: string
          description: Verblijfsnummer
        sequence_in_stay:
          type: integer
          description: Volgordenummer van de reis binnen het verblijf
          format: int32
        operational_length:
          type: number
          description: Lengte over alles
          format: double
        operational_breadth:
          type: number
          description: Grootste breedte
          format: double
        operational_draught_bow:
          type: number
          description: Operationele diepgang voor
          format: double
        operational_draught_stern:
          type: number
          description: Operationele diepgang achter
          format: double
        agent:
          type: string
          description: Scheepsagent
        agent_name:
          type: string
          description: Naam scheepsagent
        previous_port_of_call:
          type: string
          description: Vorige aanloophaven
        previous_port_of_call_name:
          type: string
          description: Vorige aanloophaven naam
        next_port_of_call:
          type: string
          description: Volgende aanloophaven
        next_port_of_call_name:
          type: string
          description: Volgende aanloophaven naam
        port_of_origin:
          type: string
          description: Haven herkomst
        port_of_origin_name:
          type: string
          description: Haven herkomst naam
        port_of_destination:
          type: string
          description: Haven bestemming
        port_of_destination_name:
          type: string
          description: Haven bestemming naam
        cbs_entry_point:
          type: string
          description: CBS Entrypoint
        cbs_entry_point_name:
          type: string
          description: CBS Entrypoint naam
        cbs_entry_point_eta:
          type: string
          description: ETA CBS Entrypoint
          format: date-time
        cbs_exit_point:
          type: string
          description: CBS Exitpoint
        cbs_exit_point_name:
          type: string
          description: CBS Exitpoint naam
        cbs_exit_point_ata:
          type: string
          description: ATA CBS Exitpoint
          format: date-time
        stay_start:
          type: string
          description: Datum/tijd start van het verblijf in de haven
          format: date-time
        stay_end:
          type: string
          description: Datum/tijd van het vertrek uit de haven
          format: date-time
        voyage_start:
          type: string
          description: Datum/tijd start reis
          format: date-time
        voyage_end:
          type: string
          description: Datum/tijd einde reis
          format: date-time
        passage_point_eta:
          type: string
          description: Naam locatie meest recente ETA
        passage_point_eta_name:
          type: string
        eta:
          type: string
          description: Datum/tijd meest recente ETA
          format: date-time
        passage_point_ata:
          type: string
          description: Locatie meest recente ATA
        passage_point_ata_name:
          type: string
          description: Naam locatie meest recente ATA
        ata:
          type: string
          description: Datum/tijd meest recente ATA
          format: date-time
        etd:
          type: string
          description: ETD
          format: date-time
        stay_cancelled:
          type: string
          description: Datum/tijd verblijf geannuleerd
          format: date-time
        stay_cancelled_reason:
          type: string
          description: Redenen verblijf geannuleerd
        voyage_cancelled:
          type: string
          description: Datum/tijd reis geannuleerd
          format: date-time
        voyage_cancelled_reason:
          type: string
          description: Redenen reis geannuleerd
        berth_of_origin:
          type: string
          description: Ligplaats vertrek
        berth_of_origin_name:
          type: string
          description: Naam ligplaats vertrek
        terminal_of_origin:
          type: string
          description: Terminal vertrek
        terminal_of_origin_name:
          type: string
          description: Naam terminal vertrek
        berth_of_destination_from:
          type: string
          description: Ligplaats bestemming van
        berth_of_destination_from_name:
          type: string
          description: Naam ligplaats bestemming van
        berth_of_destination_to:
          type: string
          description: Ligplaats bestemming tot
        berth_of_destination_to_name:
          type: string
          description: naam_ligplaats bestemming tot
        terminal_of_destination:
          type: string
          description: Terminal bestemming
        terminal_of_destination_name:
          type: string
          description: Naam terminal bestemming
        mooring_side:
          type: string
          description: Meerzijde
        mooring_position:
          type: string
          description: Meerpositie
        route_category:
          type: string
          description: Soort reis
        voyage_state:
          type: string
          description: Status reis
        incoming_mode:
          type: string
          description: Opvaarttype
        ship:
          description: Schip
          $ref: '#/components/schemas/PortVoyageShipResponseDTO'
        persons_on_board:
          $ref: '#/components/schemas/PortVoyagePersonsOnBoardResponseDTO'
        pts:
          type: array
          items:
            $ref: '#/components/schemas/PtaResponseDTO'
        locks:
          type: array
          items:
            $ref: '#/components/schemas/LockResponseDTO'
        travel_plans:
          type: array
          items:
            $ref: '#/components/schemas/TravelPlanResponseDTO'
    PortStayShipResponseDTO:
      type: object
      properties:
        ship_name:
          type: string
          description: Naam schip
        imo_number:
          type: string
          description: IMO nummer
        call_sign:
          type: string
          description: Callsign
        ship_type:
          type: string
          description: Scheepstype
    PortStayResponseDTO:
      type: object
      properties:
        stay_number:
          type: string
          description: Verblijfsnummer
        previous_port_of_call:
          type: string
          description: Vorige aanloophaven
        next_port_of_call:
          type: string
          description: Volgende aanloophaven
        cbs_entry_point:
          type: string
          description: CBS Entrypoint
        cbs_entry_point_eta:
          type: string
          description: ETA CBS Entrypoint
          format: date-time
        etd:
          type: string
          description: ETD
          format: date-time
        stay_start:
          type: string
          description: Datum/tijd start van het verblijf in de haven
          format: date-time
        stay_end:
          type: string
          description: Datum/tijd van het vertrek uit de haven
          format: date-time
        berth_at_arrival:
          type: string
          description: Ligplaats bij aankomst
        berth_at_departure:
          type: string
          description: Ligplaats bij vertrek
        ship:
          description: Schip
          $ref: '#/components/schemas/PortStayShipResponseDTO'
    Problem:
      type: object
      properties:
        detail:
          type: string
        title:
          type: string
        status:
          type: integer
          format: int32
    PortOfAntwerpProblem:
      type: object
      properties:
        stacktrace:
          type: string
        message:
          type: string
