---
swagger: '2.0'
info:
  version: v1
  title: NxtPort VGM API
  description: The VGM API provides information about the verified gross mass of a
    container currently used in an export flow, as provided by certified weighing
    stations.
host: api-sb.nxtport.eu
basePath: "/VGM/v1"
securityDefinitions:
  apiKeyHeader:
    type: apiKey
    name: Ocp-Apim-Subscription-Key
    in: header
security:
  - apiKeyHeader: []
schemes:
  - https
paths:
  "/nxtportdocument/{bookingnumber}/{containernumber}":
    get:
      tags:
      - Document
      summary: Returns the VERMAS files with the according bookingnumber and containernumber
      operationId: NxtportdocumentByBookingnumberByContainernumberGet
      consumes: []
      produces:
      - application/json
      - application/xml
      parameters:
      - name: bookingnumber
        in: path
        description: bookingnumber
        required: true
        type: string
      - name: containernumber
        in: path
        description: containernumber
        required: true
        type: string
      - name: Ocp-Apim-Subscription-Key
        in: header
        required: false
        type: string
      responses:
        '200':
          description: Success
          schema:
            "$ref": "#/definitions/ContainerWeightInfo"
  "/ping":
    get:
      tags:
      - Document
      operationId: PingGet
      consumes: []
      produces: []
      parameters:
      - name: Ocp-Apim-Subscription-Key
        in: header
        required: false
        type: string
      responses:
        '200':
          description: Success
  "/nxtportdocument/subscribe":
    post:
      tags:
      - Document
      summary: Registers an alert for VGM assets.
      operationId: NxtportdocumentSubscribePost
      consumes:
      - application/json
      produces: []
      parameters:
      - name: subscription
        in: body
        required: false
        schema:
          "$ref": "#/definitions/VgmNotificationSubscription"
      - name: Ocp-Apim-Subscription-Key
        in: header
        required: false
        type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '500':
          description: Server Error
definitions:
  ContainerWeightInfo:
    type: object
    properties:
      disclaimer:
        type: string
      references:
        "$ref": "#/definitions/References"
      submitter:
        "$ref": "#/definitions/Submitter"
      verifiedGrossMass:
        "$ref": "#/definitions/VerifiedGrossMass"
      seals:
        type: array
        items:
          "$ref": "#/definitions/Seal"
      parties:
        type: array
        items:
          "$ref": "#/definitions/Party"
  References:
    type: object
    properties:
      bookingId:
        type: string
      containerId:
        type: string
      parentDocument:
        "$ref": "#/definitions/ParentDocument"
  Submitter:
    type: object
    properties:
      party:
        "$ref": "#/definitions/Party"
  VerifiedGrossMass:
    type: object
    properties:
      value:
        type: string
      uom:
        type: string
      weighingDate:
        type: string
      weighingTime:
        type: string
      verificationMethod:
        type: string
  Seal:
    type: object
    properties:
      sealPartyTypeCode:
        type: string
      sealNumber:
        type: string
  Party:
    type: object
    properties:
      partyTypeCode:
        type: string
      name:
        type: string
      scac:
        type: string
      eori:
        type: string
      streetAndNumber:
        type: string
      postalCode:
        type: string
      place:
        type: string
      countryCode:
        type: string
      unstructuredAddress:
        type: string
      contacts:
        type: array
        items:
          "$ref": "#/definitions/Contact"
  ParentDocument:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      senderId:
        type: string
  Contact:
    type: object
    properties:
      contactTypeCode:
        type: string
      name:
        type: string
  VgmNotificationSubscription:
    type: object
    properties:
      subscriptions:
        description: The NxtPort.Services.Consumption.API.VGM.Models.BookingNumberSubscription
          elements that define the VGM assets on which to alert.
        type: array
        items:
          "$ref": "#/definitions/BookingNumberSubscription"
      channels:
        type: array
        items:
          "$ref": "#/definitions/Channel"
  BookingNumberSubscription:
    required:
    - bookingNumber
    - containerNumber
    type: object
    properties:
      bookingNumber:
        type: string
      containerNumber:
        type: string
  Channel:
    required:
    - type
    - address
    type: object
    properties:
      type:
        enum:
        - Email
        - Webhook
        - AS2
        type: string
      address:
        type: string
